c_compiler_version:        # [linux]
  - 14                     # [linux]
cxx_compiler_version:      # [linux]
  - 14                     # [linux]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
arm_variant_target:
  - None
  - sbsa                   # [linux]
#  - tegra                  # [linux]
cross_target_platform:
  - None           # [not (linux or win)]
  - linux-64       # [linux]
  - linux-aarch64  # [linux]
#  - linux-aarch64  # [linux]
  - win-64         # [win]
# https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#virtual-architecture-feature-list
# https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#gpu-feature-list
DEFAULT_CUDAARCHS:
  - "75-real;80-real;86-real;89-real;90a-real;100f-real;103f-real;120a-real;121f-real;121-virtual"
  - "75-real;80-real;86-real;89-real;90a-real;100f-real;103f-real;120a-real;121f-real;121-virtual"  # [linux]
#  - "72-real;87-real;110"  # [linux]
DEFAULT_TORCH_CUDA_ARCH_LIST:
  - "7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0;12.1+PTX"
  - "7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0;12.1+PTX"  # [linux]
#  - "8.7;11.0+PTX"  # [linux]

zip_keys:
  - arm_variant_target
  - cross_target_platform
  - DEFAULT_CUDAARCHS
  - DEFAULT_TORCH_CUDA_ARCH_LIST
