c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
arm_variant_target:
  - None
  - sbsa                   # [linux]
  - tegra                  # [linux]
cross_target_platform:
  - None           # [not (linux or win)]
  - linux-64       # [linux]
  - linux-aarch64  # [linux]
  - linux-aarch64  # [linux]
  - win-64         # [win]
# https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#virtual-architecture-feature-list
# https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#gpu-feature-list
DEFAULT_CUDAARCHS:
  - "50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90-real;100-real;101-real;103-real;120-real;121"
  - "50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90-real;100-real;101-real;103-real;120-real;121"  # [linux]
  - "72-real;87"  # [linux]
DEFAULT_TORCH_CUDA_ARCH_LIST:
  - "5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0;10.0;10.1;10.3;12.0;12.1+PTX"
  - "5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0;10.0;10.1;10.3;12.0;12.1+PTX"  # [linux]
  - "7.2;8.7+PTX"  # [linux]

zip_keys:
  - arm_variant_target
  - cross_target_platform
  - DEFAULT_CUDAARCHS
  - DEFAULT_TORCH_CUDA_ARCH_LIST
